// apps/template/frontend/src/app/presentation/components/demo/InfiniteScrollDemo.vue
<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue'
import { useInfiniteQuery } from '@tanstack/vue-query'
import { useI18n } from 'vue-i18n'

import { getPaginatedItemsDemoItemsGet } from '@/gen/client'
import type { PaginatedResponse } from '@/gen/models'
import DemoSection from './DemoSection.vue'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'

const { t } = useI18n()
const sentinelRef = ref<HTMLDivElement | null>(null)

const {
  data,
  fetchNextPage,
  hasNextPage,
  isFetchingNextPage,
  isLoading,
  isError,
  refetch,
} = useInfiniteQuery({
  queryKey: ['demo', 'infinite-items'],
  queryFn: async ({ pageParam }) => {
    return getPaginatedItemsDemoItemsGet({
      cursor: pageParam,
      limit: 5,
      delay_ms: 500,
    })
  },
  initialPageParam: 0,
  getNextPageParam: (lastPage: PaginatedResponse) => lastPage.next_cursor,
})

const allItems = computed(() => data.value?.pages.flatMap((page) => page.items) ?? [])
const total = computed(() => data.value?.pages[0]?.total ?? 0)

let observer: IntersectionObserver | null = null

// Watch for sentinel element availability (it's inside a conditional template)
watch(sentinelRef, (el) => {
  // Cleanup previous observer
  observer?.disconnect()

  if (!el) return

  observer = new IntersectionObserver(
    (entries) => {
      if (entries[0]?.isIntersecting && hasNextPage.value && !isFetchingNextPage.value) {
        fetchNextPage()
      }
    },
    { threshold: 0.1 }
  )

  observer.observe(el)
})

onUnmounted(() => {
  observer?.disconnect()
})
</script>

<template>
  <DemoSection icon="&#128214;" :title="t('demo.infiniteScroll.title')">
    <div class="space-y-4">
      <div class="flex items-center gap-4 text-sm">
        <span>
          <span class="font-mono">loaded:</span>
          {{ allItems.length }}/{{ total }}
        </span>
        <span>
          <span class="font-mono">hasMore:</span>
          <span :class="hasNextPage ? 'text-green-500' : 'text-muted-foreground'">
            {{ String(hasNextPage) }}
          </span>
        </span>
      </div>

      <div class="bg-muted rounded-lg p-3 max-h-[200px] overflow-y-auto space-y-2">
        <template v-if="isLoading">
          <Skeleton class="h-10 w-full rounded animate-pulse" />
          <Skeleton class="h-10 w-full rounded animate-pulse" />
          <Skeleton class="h-10 w-full rounded animate-pulse" />
        </template>
        <template v-else-if="isError">
          <div class="text-center py-4 motion-preset-shake motion-duration-[0.4s]">
            <p class="text-destructive mb-2">{{ t('demo.infiniteScroll.error') }}</p>
            <Button size="sm" variant="outline" class="active:scale-95 hover:-translate-y-0.5 hover:shadow-md transition-all duration-150" @click="refetch()">
              {{ t('demo.infiniteScroll.retry') }}
            </Button>
          </div>
        </template>
        <template v-else-if="allItems.length === 0">
          <p class="text-muted-foreground text-center py-4">{{ t('demo.infiniteScroll.empty') }}</p>
        </template>
        <template v-else>
          <div
            v-for="(item, index) in allItems"
            :key="item.id"
            class="bg-background rounded p-2 text-sm motion-preset-slide-up motion-duration-[0.2s]"
            :style="{ animationDelay: `${(index % 5) * 50}ms` }"
          >
            <span class="font-medium">{{ item.title }}</span>
            <span class="text-muted-foreground ml-2">- {{ item.description }}</span>
          </div>
          <!-- Sentinel element for intersection observer -->
          <div ref="sentinelRef" class="h-1" />
        </template>

        <div v-if="isFetchingNextPage" class="space-y-2">
          <Skeleton class="h-10 w-full rounded animate-pulse" />
          <Skeleton class="h-10 w-full rounded animate-pulse" />
        </div>
      </div>

      <p class="text-xs text-muted-foreground">{{ t('demo.infiniteScroll.note') }}</p>
    </div>
  </DemoSection>
</template>

// apps/template-react/frontend/components/demo/InfiniteScrollDemo.tsx
'use client';

import { useEffect, useRef } from 'react';
import { useInfiniteQuery } from '@tanstack/react-query';
import { useTranslations } from 'next-intl';

import { getPaginatedItemsDemoItemsGet } from '@/src/gen/client/getPaginatedItemsDemoItemsGet';
import type { PaginatedResponse } from '@/src/gen/models/PaginatedResponse';
import { DemoSection } from './DemoSection';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

export function InfiniteScrollDemo() {
  const t = useTranslations('demo.infiniteScroll');
  const sentinelRef = useRef<HTMLDivElement>(null);

  const {
    data,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    isLoading,
    isError,
    refetch,
  } = useInfiniteQuery({
    queryKey: ['demo', 'infinite-items'],
    queryFn: async ({ pageParam }) => {
      return getPaginatedItemsDemoItemsGet({
        cursor: pageParam,
        limit: 5,
        delay_ms: 500,
      });
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage: PaginatedResponse) => lastPage.next_cursor,
  });

  // Auto-fetch on scroll using IntersectionObserver
  useEffect(() => {
    const sentinel = sentinelRef.current;
    if (!sentinel) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting && hasNextPage && !isFetchingNextPage) {
          void fetchNextPage();
        }
      },
      { threshold: 0.1 }
    );

    observer.observe(sentinel);
    return () => { observer.disconnect(); };
  }, [hasNextPage, isFetchingNextPage, fetchNextPage]);

  const allItems = data?.pages.flatMap((page) => page.items) ?? [];
  const total = data?.pages[0]?.total ?? 0;

  return (
    <DemoSection icon="&#128214;" title={t('title')}>
      <div className="space-y-4">
        <div className="flex items-center gap-4 text-sm">
          <span>
            <span className="font-mono">loaded:</span>{' '}
            <span>{allItems.length}/{total}</span>
          </span>
          <span>
            <span className="font-mono">hasMore:</span>{' '}
            <span className={hasNextPage ? 'text-green-500' : 'text-muted-foreground'}>
              {String(hasNextPage)}
            </span>
          </span>
        </div>

        <div className="bg-muted rounded-lg p-3 max-h-[200px] overflow-y-auto space-y-2">
          {isLoading ? (
            <>
              <Skeleton className="h-10 w-full rounded animate-pulse" />
              <Skeleton className="h-10 w-full rounded animate-pulse" />
              <Skeleton className="h-10 w-full rounded animate-pulse" />
            </>
          ) : isError ? (
            <div className="text-center py-4 motion-preset-shake motion-duration-[0.4s]">
              <p className="text-destructive mb-2">{t('error')}</p>
              <Button
                size="sm"
                variant="outline"
                onClick={() => refetch()}
                className="active:scale-95 hover:-translate-y-0.5 hover:shadow-md transition-all duration-150"
              >
                {t('retry')}
              </Button>
            </div>
          ) : allItems.length === 0 ? (
            <p className="text-muted-foreground text-center py-4">{t('empty')}</p>
          ) : (
            <>
              {allItems.map((item, index) => (
                <div
                  key={item.id}
                  className="bg-background rounded p-2 text-sm motion-preset-slide-up motion-duration-[0.2s]"
                  style={{ animationDelay: `${String((index % 5) * 50)}ms` }}
                >
                  <span className="font-medium">{item.title}</span>
                  <span className="text-muted-foreground ml-2">- {item.description}</span>
                </div>
              ))}
              {/* Sentinel element for intersection observer */}
              <div ref={sentinelRef} className="h-1" />
            </>
          )}

          {isFetchingNextPage && (
            <div className="space-y-2">
              <Skeleton className="h-10 w-full rounded animate-pulse" />
              <Skeleton className="h-10 w-full rounded animate-pulse" />
            </div>
          )}
        </div>

        <p className="text-xs text-muted-foreground">{t('note')}</p>
      </div>
    </DemoSection>
  );
}
