// apps/template/frontend/src/app/presentation/components/demo/ParallelQueriesDemo.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useQueries } from '@tanstack/vue-query'
import { useI18n } from 'vue-i18n'
import { Cloud, TrendingUp, Newspaper, RefreshCw } from 'lucide-vue-next'

import {
  getWeatherDemoWeatherGetQueryOptions,
  getStockDemoStockGetQueryOptions,
  getNewsDemoNewsGetQueryOptions,
} from '@/gen/hooks'
import DemoSection from './DemoSection.vue'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'

const { t } = useI18n()

const results = useQueries({
  queries: [
    {
      ...getWeatherDemoWeatherGetQueryOptions({ city: 'Moscow', delay_ms: 800 }),
      staleTime: 30000,
    },
    {
      ...getStockDemoStockGetQueryOptions({ symbol: 'DEMO', delay_ms: 600 }),
      staleTime: 30000,
    },
    {
      ...getNewsDemoNewsGetQueryOptions({ delay_ms: 700 }),
      staleTime: 30000,
    },
  ],
})

const weatherQuery = computed(() => results.value[0])
const stockQuery = computed(() => results.value[1])
const newsQuery = computed(() => results.value[2])

const isAnyFetching = computed(() => results.value.some((r) => r.isFetching))
const loadedCount = computed(() => results.value.filter((r) => r.data).length)

const refetchAll = () => {
  results.value.forEach((r) => r.refetch())
}
</script>

<template>
  <DemoSection icon="&#9881;" :title="t('demo.parallel.title')">
    <div class="space-y-4">
      <div class="flex items-center gap-4 text-sm">
        <span>
          <span class="font-mono">loaded:</span>
          {{ loadedCount }}/3
        </span>
        <span>
          <span class="font-mono">fetching:</span>
          <span :class="isAnyFetching ? 'text-blue-500' : 'text-muted-foreground'">
            {{ String(isAnyFetching) }}
          </span>
        </span>
      </div>

      <div class="grid gap-3">
        <!-- Weather Card -->
        <div class="bg-muted rounded-lg p-3">
          <div class="flex items-center gap-2 mb-2">
            <Cloud class="w-4 h-4 text-blue-500" />
            <span class="text-sm font-medium">{{ t('demo.parallel.weather') }}</span>
            <span v-if="weatherQuery?.isFetching" class="text-xs text-blue-500 ml-auto">
              {{ t('demo.parallel.loading') }}
            </span>
          </div>
          <Skeleton v-if="weatherQuery?.isLoading" class="h-8 w-full" />
          <div
            v-else-if="weatherQuery?.data"
            class="flex items-baseline gap-2 motion-preset-fade motion-duration-[0.2s]"
          >
            <span class="text-2xl font-bold">{{ weatherQuery.data.temperature }}°C</span>
            <span class="text-muted-foreground">{{ weatherQuery.data.condition }}</span>
            <span class="text-xs text-muted-foreground ml-auto">
              {{ weatherQuery.data.city }}
            </span>
          </div>
        </div>

        <!-- Stock Card -->
        <div class="bg-muted rounded-lg p-3">
          <div class="flex items-center gap-2 mb-2">
            <TrendingUp class="w-4 h-4 text-green-500" />
            <span class="text-sm font-medium">{{ t('demo.parallel.stock') }}</span>
            <span v-if="stockQuery?.isFetching" class="text-xs text-blue-500 ml-auto">
              {{ t('demo.parallel.loading') }}
            </span>
          </div>
          <Skeleton v-if="stockQuery?.isLoading" class="h-8 w-full" />
          <div
            v-else-if="stockQuery?.data"
            class="flex items-baseline gap-2 motion-preset-fade motion-duration-[0.2s]"
          >
            <span class="text-2xl font-bold">${{ stockQuery.data.price }}</span>
            <span :class="stockQuery.data.change >= 0 ? 'text-green-500' : 'text-red-500'">
              {{ stockQuery.data.change >= 0 ? '+' : '' }}{{ stockQuery.data.change }}%
            </span>
            <span class="text-xs text-muted-foreground ml-auto">
              {{ stockQuery.data.symbol }}
            </span>
          </div>
        </div>

        <!-- News Card -->
        <div class="bg-muted rounded-lg p-3">
          <div class="flex items-center gap-2 mb-2">
            <Newspaper class="w-4 h-4 text-orange-500" />
            <span class="text-sm font-medium">{{ t('demo.parallel.news') }}</span>
            <span v-if="newsQuery?.isFetching" class="text-xs text-blue-500 ml-auto">
              {{ t('demo.parallel.loading') }}
            </span>
          </div>
          <Skeleton v-if="newsQuery?.isLoading" class="h-8 w-full" />
          <div v-else-if="newsQuery?.data" class="motion-preset-fade motion-duration-[0.2s]">
            <p class="text-sm font-medium line-clamp-1">
              {{ newsQuery.data.headline }}
            </p>
            <p class="text-xs text-muted-foreground">{{ newsQuery.data.source }}</p>
          </div>
        </div>
      </div>

      <Button
        variant="outline"
        :disabled="isAnyFetching"
        class="w-full active:scale-[0.98] transition-transform duration-100"
        @click="refetchAll"
      >
        <RefreshCw class="w-4 h-4 mr-2" :class="isAnyFetching ? 'animate-spin' : ''" />
        {{ t('demo.parallel.refetchAll') }}
      </Button>

      <p class="text-xs text-muted-foreground">{{ t('demo.parallel.note') }}</p>
    </div>
  </DemoSection>
</template>

// apps/template-react/frontend/components/demo/ParallelQueriesDemo.tsx
'use client';

import { useQueries } from '@tanstack/react-query';
import { useTranslations } from 'next-intl';
import { Cloud, TrendingUp, Newspaper, RefreshCw } from 'lucide-react';

import {
  getWeatherDemoWeatherGetQueryOptions,
  getStockDemoStockGetQueryOptions,
  getNewsDemoNewsGetQueryOptions,
} from '@/src/gen/hooks';
import { DemoSection } from './DemoSection';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

export function ParallelQueriesDemo() {
  const t = useTranslations('demo.parallel');

  const results = useQueries({
    queries: [
      {
        ...getWeatherDemoWeatherGetQueryOptions({ city: 'Moscow', delay_ms: 800 }),
        staleTime: 30000,
      },
      {
        ...getStockDemoStockGetQueryOptions({ symbol: 'DEMO', delay_ms: 600 }),
        staleTime: 30000,
      },
      {
        ...getNewsDemoNewsGetQueryOptions({ delay_ms: 700 }),
        staleTime: 30000,
      },
    ],
  });

  const [weatherQuery, stockQuery, newsQuery] = results;

  const isAnyFetching = results.some((r) => r.isFetching);
  const loadedCount = results.filter((r) => r.data).length;

  const refetchAll = () => {
    results.forEach((r) => { void r.refetch(); });
  };

  return (
    <DemoSection icon="&#9881;" title={t('title')}>
      <div className="space-y-4">
        <div className="flex items-center gap-4 text-sm">
          <span>
            <span className="font-mono">loaded:</span>{' '}
            <span>{loadedCount}/3</span>
          </span>
          <span>
            <span className="font-mono">fetching:</span>{' '}
            <span className={isAnyFetching ? 'text-blue-500' : 'text-muted-foreground'}>
              {String(isAnyFetching)}
            </span>
          </span>
        </div>

        <div className="grid gap-3">
          {/* Weather Card */}
          <div
            className="bg-muted rounded-lg p-3 motion-preset-slide-up motion-duration-[0.3s]"
            style={{ animationDelay: '0ms' }}
          >
            <div className="flex items-center gap-2 mb-2">
              <Cloud className="w-4 h-4 text-blue-500" />
              <span className="text-sm font-medium">{t('weather')}</span>
              {weatherQuery.isFetching && (
                <span className="text-xs text-blue-500 ml-auto animate-pulse">{t('loading')}</span>
              )}
            </div>
            {weatherQuery.isLoading ? (
              <Skeleton className="h-8 w-full" />
            ) : weatherQuery.data ? (
              <div className="flex items-baseline gap-2 motion-preset-fade motion-duration-[0.2s]">
                <span className="text-2xl font-bold">{weatherQuery.data.temperature}°C</span>
                <span className="text-muted-foreground">{weatherQuery.data.condition}</span>
                <span className="text-xs text-muted-foreground ml-auto">
                  {weatherQuery.data.city}
                </span>
              </div>
            ) : null}
          </div>

          {/* Stock Card */}
          <div
            className="bg-muted rounded-lg p-3 motion-preset-slide-up motion-duration-[0.3s]"
            style={{ animationDelay: '100ms' }}
          >
            <div className="flex items-center gap-2 mb-2">
              <TrendingUp className="w-4 h-4 text-green-500" />
              <span className="text-sm font-medium">{t('stock')}</span>
              {stockQuery.isFetching && (
                <span className="text-xs text-blue-500 ml-auto animate-pulse">{t('loading')}</span>
              )}
            </div>
            {stockQuery.isLoading ? (
              <Skeleton className="h-8 w-full" />
            ) : stockQuery.data ? (
              <div className="flex items-baseline gap-2 motion-preset-fade motion-duration-[0.2s]">
                <span className="text-2xl font-bold">${stockQuery.data.price}</span>
                <span
                  className={
                    stockQuery.data.change >= 0
                      ? 'text-green-500 motion-preset-bounce motion-duration-[0.3s]'
                      : 'text-red-500 motion-preset-shake motion-duration-[0.3s]'
                  }
                  key={stockQuery.data.change}
                >
                  {stockQuery.data.change >= 0 ? '+' : ''}
                  {stockQuery.data.change}%
                </span>
                <span className="text-xs text-muted-foreground ml-auto">
                  {stockQuery.data.symbol}
                </span>
              </div>
            ) : null}
          </div>

          {/* News Card */}
          <div
            className="bg-muted rounded-lg p-3 motion-preset-slide-up motion-duration-[0.3s]"
            style={{ animationDelay: '200ms' }}
          >
            <div className="flex items-center gap-2 mb-2">
              <Newspaper className="w-4 h-4 text-orange-500" />
              <span className="text-sm font-medium">{t('news')}</span>
              {newsQuery.isFetching && (
                <span className="text-xs text-blue-500 ml-auto animate-pulse">{t('loading')}</span>
              )}
            </div>
            {newsQuery.isLoading ? (
              <Skeleton className="h-8 w-full" />
            ) : newsQuery.data ? (
              <div className="motion-preset-fade motion-duration-[0.2s]">
                <p className="text-sm font-medium line-clamp-1">
                  {newsQuery.data.headline}
                </p>
                <p className="text-xs text-muted-foreground">{newsQuery.data.source}</p>
              </div>
            ) : null}
          </div>
        </div>

        <Button
          variant="outline"
          disabled={isAnyFetching}
          className="w-full active:scale-[0.98] hover:-translate-y-0.5 hover:shadow-md transition-all duration-150"
          onClick={refetchAll}
        >
          <RefreshCw className={`w-4 h-4 mr-2 ${isAnyFetching ? 'animate-spin' : ''}`} />
          {t('refetchAll')}
        </Button>

        <p className="text-xs text-muted-foreground">{t('note')}</p>
      </div>
    </DemoSection>
  );
}
