// apps/template-react/frontend/components/demo/LoadingDemo.tsx
'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';

import { useSlowEndpointDemoSlowGet } from '@/src/gen/hooks';
import { DemoSection } from './DemoSection';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

export function LoadingDemo() {
  const t = useTranslations('demo.loading');
  const [hasTriggered, setHasTriggered] = useState(false);

  const { data, isFetching, refetch } = useSlowEndpointDemoSlowGet(
    { delay_ms: 2000 },
    { query: { enabled: hasTriggered } }
  );

  // Only show loading when actually fetching (not when query is just disabled)
  const isLoading = hasTriggered && isFetching;

  const triggerLoad = () => {
    setHasTriggered(true);
    void refetch();
  };

  return (
    <DemoSection icon="&#9203;" title={t('title')}>
      <div className="space-y-4">
        <div className="flex items-center gap-2 text-sm">
          <span className="font-mono">isFetching:</span>
          <span className={isLoading
              ? 'text-yellow-500 motion-preset-pulse motion-duration-[1s] motion-loop-infinite'
              : 'text-green-500'}>
            {String(isLoading)}
          </span>
        </div>

        <div className="bg-muted rounded-lg p-4 min-h-[80px]">
          {isLoading ? (
            <>
              <Skeleton className="h-4 w-3/4 mb-2" />
              <Skeleton className="h-4 w-1/2" />
            </>
          ) : data ? (
            <div className="motion-preset-fade motion-preset-slide-up-sm motion-duration-[0.3s]">
              <p className="font-medium">{data.message}</p>
              <p className="text-xs text-muted-foreground mt-1">
                {t('loadedAt')}: {data.timestamp}
              </p>
            </div>
          ) : (
            <p className="text-muted-foreground">{t('clickToLoad')}</p>
          )}
        </div>

        <div className="flex gap-2">
          <Button
            disabled={isLoading}
            onClick={triggerLoad}
            className="active:scale-95 hover:-translate-y-0.5 hover:shadow-md hover:shadow-primary/20 transition-all duration-150"
          >
            {isLoading ? t('loading') : t('trigger')}
          </Button>
        </div>
      </div>
    </DemoSection>
  );
}

// apps/template/frontend/src/app/presentation/components/demo/LoadingDemo.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useSlowEndpointDemoSlowGet } from '@/gen/hooks'
import DemoSection from './DemoSection.vue'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'

const { t } = useI18n()
const hasTriggered = ref(false)

const { data, isFetching, refetch } = useSlowEndpointDemoSlowGet(
  { delay_ms: 2000 },
  { query: { enabled: () => hasTriggered.value } }
)

// Only show loading when actually fetching (not when query is just disabled)
const isLoading = computed(() => hasTriggered.value && isFetching.value)

const triggerLoad = () => {
  hasTriggered.value = true
  refetch()
}
</script>

<template>
  <DemoSection icon="&#9203;" :title="t('demo.loading.title')">
    <div class="space-y-4">
      <div class="flex items-center gap-2 text-sm">
        <span class="font-mono">isFetching:</span>
        <span
:class="isLoading
          ? 'text-yellow-500 motion-preset-pulse motion-duration-[1s] motion-loop-infinite'
          : 'text-green-500'">
          {{ isLoading }}
        </span>
      </div>

      <div class="bg-muted rounded-lg p-4 min-h-[80px]">
        <template v-if="isLoading">
          <Skeleton class="h-4 w-3/4 mb-2" />
          <Skeleton class="h-4 w-1/2" />
        </template>
        <div v-else-if="data" class="motion-preset-fade motion-preset-slide-up-sm motion-duration-[0.3s]">
          <p class="font-medium">{{ data.message }}</p>
          <p class="text-xs text-muted-foreground mt-1">
            {{ t('demo.loading.loadedAt') }}: {{ data.timestamp }}
          </p>
        </div>
        <template v-else>
          <p class="text-muted-foreground">{{ t('demo.loading.clickToLoad') }}</p>
        </template>
      </div>

      <div class="flex gap-2">
        <Button :disabled="isLoading" class="active:scale-95 hover:-translate-y-0.5 hover:shadow-md hover:shadow-primary/20 transition-all duration-150" @click="triggerLoad">
          {{ isLoading ? t('demo.loading.loading') : t('demo.loading.trigger') }}
        </Button>
      </div>
    </div>
  </DemoSection>
</template>
