// apps/template-react/frontend/components/demo/PollingDemo.tsx
'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';

import { useGetServerTimeDemoTimeGet } from '@/src/gen/hooks';
import { DemoSection } from './DemoSection';
import { Button } from '@/components/ui/button';

const POLL_INTERVALS = [
  { label: 'Off', value: 0 },
  { label: '1s', value: 1000 },
  { label: '2s', value: 2000 },
  { label: '5s', value: 5000 },
];

export function PollingDemo() {
  const t = useTranslations('demo.polling');
  const [pollInterval, setPollInterval] = useState(0);

  const { data, isFetching, dataUpdatedAt } = useGetServerTimeDemoTimeGet({
    query: {
      refetchInterval: pollInterval > 0 ? pollInterval : false,
      refetchIntervalInBackground: false,
    },
  });

  return (
    <DemoSection icon="&#128260;" title={t('title')}>
      <div className="space-y-4">
        <div className="flex items-center gap-4 text-sm">
          <span className="flex items-center gap-2">
            <span className="font-mono">polling:</span>
            <span className={`inline-flex items-center gap-1.5 ${
              pollInterval > 0 ? 'text-green-500' : 'text-muted-foreground'
            }`}>
              {pollInterval > 0 && (
                <span className="w-2 h-2 bg-green-500 rounded-full motion-preset-pulse motion-duration-[1s] motion-loop-infinite" />
              )}
              {pollInterval > 0 ? `${String(pollInterval)}ms` : 'off'}
            </span>
          </span>
          <span>
            <span className="font-mono">isFetching:</span>{' '}
            <span className={isFetching ? 'text-blue-500' : 'text-muted-foreground'}>
              {String(isFetching)}
            </span>
          </span>
        </div>

        <div className={`bg-muted rounded-lg p-4 transition-shadow duration-500 ${
          pollInterval > 0 ? 'animate-pulse-glow' : ''
        }`}>
          <div className="text-center">
            <p
              className="text-4xl font-mono font-bold motion-preset-fade motion-duration-[0.15s]"
              key={data?.formatted}
            >
              {data?.formatted ?? '--:--:--'}
            </p>
            <p className="text-xs text-muted-foreground mt-2">
              {t('serverTime')}
            </p>
            {dataUpdatedAt && (
              <p className="text-xs text-muted-foreground">
                {t('lastUpdate')}: {new Date(dataUpdatedAt).toLocaleTimeString()}
              </p>
            )}
          </div>
        </div>

        <div className="flex gap-2 flex-wrap">
          {POLL_INTERVALS.map((interval) => (
            <Button
              key={interval.value}
              variant={pollInterval === interval.value ? 'default' : 'outline'}
              size="sm"
              className={`active:scale-95 hover:-translate-y-0.5 hover:shadow-md hover:shadow-primary/20 transition-all duration-150 ${
                pollInterval === interval.value ? 'motion-preset-pop motion-duration-[0.15s]' : ''
              }`}
              onClick={() => { setPollInterval(interval.value); }}
            >
              {interval.label}
            </Button>
          ))}
        </div>

        <p className="text-xs text-muted-foreground">{t('note')}</p>
      </div>
    </DemoSection>
  );
}

// apps/template-vue/frontend/src/app/presentation/components/demo/PollingDemo.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { useI18n } from 'vue-i18n'

import { getServerTimeDemoTimeGet } from '@/gen/client'
import DemoSection from './DemoSection.vue'
import { Button } from '@/components/ui/button'

const POLL_INTERVALS = [
  { label: 'Off', value: 0 },
  { label: '1s', value: 1000 },
  { label: '2s', value: 2000 },
  { label: '5s', value: 5000 },
]

const { t } = useI18n()
const pollInterval = ref(0)

// Computed for reactive refetchInterval
const refetchInterval = computed(() => (pollInterval.value > 0 ? pollInterval.value : false))

// Use useQuery directly for reactive refetchInterval support
const { data, isFetching, dataUpdatedAt } = useQuery({
  queryKey: ['demo', 'server-time'],
  queryFn: () => getServerTimeDemoTimeGet(),
  refetchInterval,
})

const formatTime = (timestamp: number) => new Date(timestamp).toLocaleTimeString()
</script>

<template>
  <DemoSection icon="&#128260;" :title="t('demo.polling.title')">
    <div class="space-y-4">
      <div class="flex items-center gap-4 text-sm">
        <span>
          <span class="font-mono">polling:</span>
          <span :class="pollInterval > 0 ? 'text-green-500' : 'text-muted-foreground'">
            {{ pollInterval > 0 ? `${pollInterval}ms` : 'off' }}
          </span>
        </span>
        <span>
          <span class="font-mono">isFetching:</span>
          <span :class="isFetching ? 'text-blue-500' : 'text-muted-foreground'">
            {{ String(isFetching) }}
          </span>
        </span>
      </div>

      <div class="bg-muted rounded-lg p-4">
        <div class="text-center">
          <p
            class="text-4xl font-mono font-bold transition-all duration-150"
            :class="isFetching ? 'opacity-50 scale-95' : 'opacity-100 scale-100'"
          >
            {{ data?.formatted ?? '--:--:--' }}
          </p>
          <p class="text-xs text-muted-foreground mt-2">
            {{ t('demo.polling.serverTime') }}
          </p>
          <p v-if="dataUpdatedAt" class="text-xs text-muted-foreground">
            {{ t('demo.polling.lastUpdate') }}: {{ formatTime(dataUpdatedAt) }}
          </p>
        </div>
      </div>

      <div class="flex gap-2 flex-wrap">
        <Button
          v-for="interval in POLL_INTERVALS"
          :key="interval.value"
          :variant="pollInterval === interval.value ? 'default' : 'outline'"
          size="sm"
          class="active:scale-95 transition-transform duration-100"
          @click="pollInterval = interval.value"
        >
          {{ interval.label }}
        </Button>
      </div>

      <p class="text-xs text-muted-foreground">{{ t('demo.polling.note') }}</p>
    </div>
  </DemoSection>
</template>
