// apps/template-react/frontend/components/demo/WebSocketDemo.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { useTranslations } from 'next-intl';
import { io, type Socket } from 'socket.io-client';

import { DemoSection } from './DemoSection';
import { Button } from '@/components/ui/button';
import { getSocketOptions } from '@/config/kubb-config';

type State = 'connecting' | 'connected' | 'disconnected' | 'reconnecting';

interface Event {
  user: string;
  delta: number;
  time: string;
}

interface UpdatePayload {
  counter: number;
  users: number;
  events: Event[];
}

function formatTimeAgo(isoTime: string): string {
  const seconds = Math.floor((Date.now() - new Date(isoTime).getTime()) / 1000);
  if (seconds < 5) return 'now';
  if (seconds < 60) return `${String(seconds)}s ago`;
  const minutes = Math.floor(seconds / 60);
  return `${String(minutes)}m ago`;
}

function formatDelta(delta: number): string {
  return delta > 0 ? `+${String(delta)}` : String(delta);
}

export function WebSocketDemo() {
  const t = useTranslations('demo.websocket');
  const [state, setState] = useState<State>('disconnected');
  const [counter, setCounter] = useState(0);
  const [users, setUsers] = useState(0);
  const [events, setEvents] = useState<Event[]>([]);
  const [reconnectAttempt, setReconnectAttempt] = useState(0);
  const socketRef = useRef<Socket | null>(null);

  // Update time display every second
  const [, setTick] = useState(0);
  useEffect(() => {
    const interval = setInterval(() => {
      setTick(t => t + 1);
    }, 1000);
    return () => {
      clearInterval(interval);
    };
  }, []);

  useEffect(() => {
    const { url, options } = getSocketOptions();
    const socket = io(url, options);
    socketRef.current = socket;
    setState('connecting');

    socket.on('connect', () => {
      setState('connected');
      setReconnectAttempt(0);
    });

    socket.on('disconnect', () => {
      setState('disconnected');
    });

    socket.on('reconnect_attempt', (attempt: number) => {
      setState('reconnecting');
      setReconnectAttempt(attempt);
    });

    socket.on('update', (data: UpdatePayload) => {
      setCounter(data.counter);
      setUsers(data.users);
      setEvents(data.events);
    });

    return () => {
      socket.disconnect();
    };
  }, []);

  const sendDelta = (delta: number) => {
    socketRef.current?.emit('increment', delta);
  };

  const stateIcon = {
    connecting: '🟡',
    connected: '🟢',
    disconnected: '🔴',
    reconnecting: '🟠',
  }[state];

  const stateText = state === 'reconnecting'
    ? `${state} (${String(reconnectAttempt)})`
    : state;

  return (
    <DemoSection icon="&#128268;" title={t('title')}>
      <div className="space-y-4">
        <div className="text-sm">
          {stateIcon} {stateText}
        </div>

        {/* Counter display */}
        <div className="bg-muted rounded-lg p-4 text-center">
          <p className="text-4xl font-mono font-bold">{counter}</p>
          <p className="text-xs text-muted-foreground mt-1">{users} {t('usersOnline')}</p>
        </div>

        {/* Action buttons */}
        <div className="flex gap-2 justify-center">
          <Button
            size="sm"
            variant="outline"
            onClick={() => { sendDelta(-1); }}
            disabled={state !== 'connected'}
          >
            -1
          </Button>
          <Button
            size="sm"
            onClick={() => { sendDelta(1); }}
            disabled={state !== 'connected'}
          >
            +1
          </Button>
          <Button
            size="sm"
            onClick={() => { sendDelta(3); }}
            disabled={state !== 'connected'}
          >
            +3
          </Button>
        </div>

        {/* Recent events */}
        {events.length > 0 && (
          <div className="space-y-1">
            <p className="text-xs font-medium text-muted-foreground">Recent activity</p>
            <div className="bg-muted/50 rounded-lg p-2 space-y-1">
              {events.slice().reverse().map((event, idx) => (
                <div
                  key={`${event.time}-${String(idx)}`}
                  className="flex items-center justify-between text-xs"
                >
                  <span className="font-medium">{event.user}</span>
                  <span className={event.delta > 0 ? 'text-green-600' : 'text-red-600'}>
                    {formatDelta(event.delta)}
                  </span>
                  <span className="text-muted-foreground w-12 text-right">
                    {formatTimeAgo(event.time)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        <p className="text-xs text-muted-foreground">
          {t('note')}
        </p>
      </div>
    </DemoSection>
  );
}

// apps/template-vue/frontend/src/app/presentation/components/demo/WebSocketDemo.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { io, type Socket } from 'socket.io-client'

import { getSocketOptions } from '@/config/kubb-config'
import DemoSection from './DemoSection.vue'
import { Button } from '@/components/ui/button'

const { t } = useI18n()

type State = 'connecting' | 'connected' | 'disconnected' | 'reconnecting'

interface Event {
  user: string
  delta: number
  time: string
}

interface UpdatePayload {
  counter: number
  users: number
  events: Event[]
}

const state = ref<State>('disconnected')
const counter = ref(0)
const users = ref(0)
const events = ref<Event[]>([])
const reconnectAttempt = ref(0)
const socketRef = ref<Socket | null>(null)
const tick = ref(0)

const stateIcon = computed(() => {
  return {
    connecting: '🟡',
    connected: '🟢',
    disconnected: '🔴',
    reconnecting: '🟠',
  }[state.value]
})

const stateText = computed(() => {
  if (state.value === 'reconnecting') {
    return `${state.value} (${reconnectAttempt.value})`
  }
  return state.value
})

function formatTimeAgo(isoTime: string): string {
  const seconds = Math.floor((Date.now() - new Date(isoTime).getTime()) / 1000)
  if (seconds < 5) return 'now'
  if (seconds < 60) return `${String(seconds)}s ago`
  const minutes = Math.floor(seconds / 60)
  return `${String(minutes)}m ago`
}

function formatDelta(delta: number): string {
  return delta > 0 ? `+${String(delta)}` : String(delta)
}

function sendDelta(delta: number) {
  socketRef.value?.emit('increment', delta)
}

let intervalId: ReturnType<typeof setInterval> | null = null

onMounted(() => {
  // Update time display every second
  intervalId = setInterval(() => {
    tick.value += 1
  }, 1000)

  const { url, options } = getSocketOptions()
  const socket = io(url, options)
  socketRef.value = socket
  state.value = 'connecting'

  socket.on('connect', () => {
    state.value = 'connected'
    reconnectAttempt.value = 0
  })

  socket.on('disconnect', () => {
    state.value = 'disconnected'
  })

  socket.on('reconnect_attempt', (attempt: number) => {
    state.value = 'reconnecting'
    reconnectAttempt.value = attempt
  })

  socket.on('update', (data: UpdatePayload) => {
    counter.value = data.counter
    users.value = data.users
    events.value = data.events
  })
})

onUnmounted(() => {
  if (intervalId) {
    clearInterval(intervalId)
  }
  socketRef.value?.disconnect()
})
</script>

<template>
  <DemoSection icon="&#128268;" :title="t('demo.websocket.title')">
    <div class="space-y-4">
      <div class="text-sm">
        {{ stateIcon }} {{ stateText }}
      </div>

      <!-- Counter display -->
      <div class="bg-muted rounded-lg p-4 text-center">
        <p class="text-4xl font-mono font-bold">{{ counter }}</p>
        <p class="text-xs text-muted-foreground mt-1">{{ users }} {{ t('demo.websocket.usersOnline') }}</p>
      </div>

      <!-- Action buttons -->
      <div class="flex gap-2 justify-center">
        <Button
          size="sm"
          variant="outline"
          :disabled="state !== 'connected'"
          @click="sendDelta(-1)"
        >
          -1
        </Button>
        <Button
          size="sm"
          :disabled="state !== 'connected'"
          @click="sendDelta(1)"
        >
          +1
        </Button>
        <Button
          size="sm"
          :disabled="state !== 'connected'"
          @click="sendDelta(3)"
        >
          +3
        </Button>
      </div>

      <!-- Recent events -->
      <div v-if="events.length > 0" class="space-y-1">
        <p class="text-xs font-medium text-muted-foreground">Recent activity</p>
        <div class="bg-muted/50 rounded-lg p-2 space-y-1">
          <div
            v-for="(event, idx) in events.slice().reverse()"
            :key="`${event.time}-${String(idx)}`"
            class="flex items-center justify-between text-xs"
          >
            <span class="font-medium">{{ event.user }}</span>
            <span :class="event.delta > 0 ? 'text-green-600' : 'text-red-600'">
              {{ formatDelta(event.delta) }}
            </span>
            <span class="text-muted-foreground w-12 text-right">
              {{ formatTimeAgo(event.time) }}
            </span>
          </div>
        </div>
      </div>

      <p class="text-xs text-muted-foreground">
        {{ t('demo.websocket.note') }}
      </p>
    </div>
  </DemoSection>
</template>
