// apps/template-react/frontend/components/profile/TelegramSection.tsx
'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';
import { Smartphone, Globe, Vibrate, X, MessageSquare } from 'lucide-react';

import { usePlatform, useTelegram } from '@/hooks';
import { ProfileSection } from './ProfileSection';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export function TelegramSection() {
  const t = useTranslations('profile.telegram');
  const platform = usePlatform();
  const telegram = useTelegram();

  const [isVibrating, setIsVibrating] = useState(false);

  const handleVibrate = () => {
    setIsVibrating(true);
    telegram.vibrate('medium');
    setTimeout(() => { setIsVibrating(false); }, 300);
  };

  const handleShowAlert = async () => {
    await telegram.showAlert(t('alertMessage'));
  };

  return (
    <ProfileSection icon="📱" title={t('title')}>
      <div className="space-y-4">
        {/* Platform Status */}
        <div className="flex items-center justify-between p-3 bg-muted rounded-lg transition-all duration-300 hover:bg-muted/80">
          <div className="flex items-center gap-3">
            {platform.isTelegram ? (
              <Smartphone className="w-5 h-5 text-blue-500" />
            ) : (
              <Globe className="w-5 h-5 text-gray-500" />
            )}
            <div>
              <p className="font-medium">{t('platform')}</p>
              <p className="text-sm text-muted-foreground">
                {platform.isTelegram ? t('telegramApp') : t('webBrowser')}
              </p>
            </div>
          </div>
          {/* Badge with pop on change */}
          <Badge
            variant={platform.isTelegram ? 'default' : 'secondary'}
            className="motion-preset-pop motion-duration-[0.2s]"
            key={platform.isTelegram ? 'telegram' : 'web'}
          >
            {platform.isTelegram ? 'Telegram' : 'Web'}
          </Badge>
        </div>

        {/* Platform Details (Telegram only) */}
        {platform.isTelegram && (
          <div className="grid grid-cols-2 gap-2 text-sm">
            <div className="bg-muted rounded-lg p-3 transition-all duration-200 hover:bg-muted/80 hover:scale-[1.02]">
              <p className="text-muted-foreground text-xs">{t('client')}</p>
              <p className="font-mono capitalize">{platform.platform}</p>
            </div>
            <div className="bg-muted rounded-lg p-3 transition-all duration-200 hover:bg-muted/80 hover:scale-[1.02]">
              <p className="text-muted-foreground text-xs">{t('colorScheme')}</p>
              <p className="capitalize">{platform.colorScheme}</p>
            </div>
          </div>
        )}

        {/* Telegram-only Actions */}
        <div className="space-y-2">
          <p className="text-sm font-medium text-muted-foreground">
            {t('actionsTitle')}
          </p>

          {platform.isTelegram ? (
            <>
              {/* Vibrate button with shake feedback */}
              <Button
                variant="outline"
                className={`w-full justify-start gap-2 active:scale-95 hover:-translate-y-0.5 hover:shadow-md hover:shadow-primary/20 transition-all duration-150 ${
                  isVibrating ? 'motion-preset-shake motion-duration-[0.3s]' : ''
                }`}
                onClick={handleVibrate}
              >
                <Vibrate className={`w-4 h-4 ${isVibrating ? 'animate-pulse' : ''}`} />
                {t('vibrate')}
              </Button>

              {/* Show Alert button */}
              <Button
                variant="outline"
                className="w-full justify-start gap-2 active:scale-95 hover:-translate-y-0.5 hover:shadow-md hover:shadow-primary/20 transition-all duration-150"
                onClick={handleShowAlert}
              >
                <MessageSquare className="w-4 h-4" />
                {t('showAlert')}
              </Button>
            </>
          ) : (
            /* Web user message */
            <div className="flex items-center gap-2 p-3 bg-muted/50 rounded-lg text-sm text-muted-foreground">
              <X className="w-4 h-4 shrink-0 opacity-50" />
              <span>{t('webOnlyMessage')}</span>
            </div>
          )}
        </div>
      </div>
    </ProfileSection>
  );
}

// apps/template-vue/frontend/src/app/presentation/components/profile/TelegramSection.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { usePlatform } from '@core/platform'
import ProfileSection from './ProfileSection.vue'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Smartphone, Globe, Vibrate, X } from 'lucide-vue-next'

const { t } = useI18n()
const platform = usePlatform()

const handleVibrate = () => {
  platform.vibrate('medium')
}

const handleShowAlert = () => {
  platform.showAlert(t('profile.telegram.alertMessage'))
}
</script>

<template>
  <ProfileSection icon="&#128241;" :title="t('profile.telegram.title')">
    <div class="space-y-4">
      <!-- Platform Status -->
      <div class="flex items-center justify-between p-3 bg-muted rounded-lg">
        <div class="flex items-center gap-3">
          <component
            :is="platform.isTelegram ? Smartphone : Globe"
            class="w-5 h-5"
            :class="platform.isTelegram ? 'text-blue-500' : 'text-gray-500'"
          />
          <div>
            <p class="font-medium">{{ t('profile.telegram.platform') }}</p>
            <p class="text-sm text-muted-foreground">
              {{ platform.isTelegram ? t('profile.telegram.telegramApp') : t('profile.telegram.webBrowser') }}
            </p>
          </div>
        </div>
        <Badge :variant="platform.isTelegram ? 'default' : 'secondary'">
          {{ platform.isTelegram ? 'Telegram' : 'Web' }}
        </Badge>
      </div>

      <!-- Platform Details (Telegram only) -->
      <div v-if="platform.isTelegram" class="grid grid-cols-2 gap-2 text-sm">
        <div class="bg-muted rounded-lg p-3">
          <p class="text-muted-foreground text-xs">{{ t('profile.telegram.client') }}</p>
          <p class="font-mono capitalize">{{ platform.telegramPlatform }}</p>
        </div>
        <div class="bg-muted rounded-lg p-3">
          <p class="text-muted-foreground text-xs">{{ t('profile.telegram.colorScheme') }}</p>
          <p class="capitalize">{{ platform.colorScheme || 'system' }}</p>
        </div>
      </div>

      <!-- Telegram-only Actions -->
      <div class="space-y-2">
        <p class="text-sm font-medium text-muted-foreground">
          {{ t('profile.telegram.actionsTitle') }}
        </p>

        <!-- Vibrate button - Telegram only -->
        <Button
          v-if="platform.isTelegram"
          variant="outline"
          class="w-full justify-start gap-2"
          @click="handleVibrate"
        >
          <Vibrate class="w-4 h-4" />
          {{ t('profile.telegram.vibrate') }}
        </Button>

        <!-- Show Alert button - Telegram only -->
        <Button
          v-if="platform.isTelegram"
          variant="outline"
          class="w-full justify-start gap-2"
          @click="handleShowAlert"
        >
          <Smartphone class="w-4 h-4" />
          {{ t('profile.telegram.showAlert') }}
        </Button>

        <!-- Web user message -->
        <div v-if="platform.isWeb" class="flex items-center gap-2 p-3 bg-muted/50 rounded-lg text-sm text-muted-foreground">
          <X class="w-4 h-4 shrink-0" />
          <span>{{ t('profile.telegram.webOnlyMessage') }}</span>
        </div>
      </div>
    </div>
  </ProfileSection>
</template>
