// apps/template-react/frontend/components/profile/UserInfoSection.tsx
'use client';

import { useState, useMemo } from 'react';
import { useTranslations } from 'next-intl';
import { useQueryClient } from '@tanstack/react-query';
import {
  LogOut,
  Smartphone,
  Mail,
  ChevronDown,
  ChevronUp,
  Flame,
  Trophy,
  Calendar,
  Check,
  Plus,
} from 'lucide-react';

import { usePlatform } from '@/hooks';
import { useLogoutAuthLogoutPost, getCurrentUserUsersMeGetQueryKey } from '@/src/gen/hooks';
import { ProfileSection } from './ProfileSection';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { LinkTelegramDialog } from './LinkTelegramDialog';
import { AddEmailDialog } from './AddEmailDialog';
import type { UserSchema } from '@/src/gen/models';

interface UserInfoSectionProps {
  user: UserSchema;
}

function StatCard({ icon: Icon, value, label }: { icon: React.ElementType; value: number; label: string }) {
  return (
    <div className="bg-muted rounded-lg p-3 text-center">
      <Icon className="h-4 w-4 mx-auto mb-1 text-muted-foreground" />
      <p className="text-2xl font-bold">{value}</p>
      <p className="text-xs text-muted-foreground">{label}</p>
    </div>
  );
}

function PreferenceRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between py-2">
      <span className="text-sm text-muted-foreground">{label}</span>
      <span className="text-sm">{value || '—'}</span>
    </div>
  );
}

function AuthMethodCard({
  icon: Icon,
  title,
  isLinked,
  subtitle,
  onLink,
  onShowDetails,
  showDetails,
  children,
}: {
  icon: React.ElementType;
  title: string;
  isLinked: boolean;
  subtitle?: string;
  onLink?: () => void;
  onShowDetails?: () => void;
  showDetails?: boolean;
  children?: React.ReactNode;
}) {
  return (
    <div className="border rounded-lg p-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-muted rounded-full p-2">
            <Icon className="h-4 w-4" />
          </div>
          <div>
            <p className="text-sm font-medium">{title}</p>
            <p className="text-xs text-muted-foreground">
              {isLinked ? subtitle : 'Not connected'}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {isLinked ? (
            <>
              <Check className="h-4 w-4 text-green-500" />
              {onShowDetails && (
                <Button variant="ghost" size="sm" onClick={onShowDetails}>
                  {showDetails ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                </Button>
              )}
            </>
          ) : (
            onLink && (
              <Button variant="outline" size="sm" onClick={onLink}>
                <Plus className="h-3 w-3 mr-1" />
                Link
              </Button>
            )
          )}
        </div>
      </div>
      {showDetails && children && (
        <div className="mt-3 pt-3 border-t space-y-1">
          {children}
        </div>
      )}
    </div>
  );
}

function DetailRow({ label, value, mono = false }: { label: string; value: unknown; mono?: boolean }) {
  let formatted: string;
  if (value === null || value === undefined) {
    formatted = '—';
  } else if (typeof value === 'boolean') {
    formatted = value ? 'Yes' : 'No';
  } else if (typeof value === 'string' || typeof value === 'number') {
    formatted = String(value);
  } else {
    formatted = JSON.stringify(value);
  }

  return (
    <div className="flex items-center justify-between text-xs">
      <span className="text-muted-foreground">{label}</span>
      <span className={mono ? 'font-mono' : ''}>{formatted}</span>
    </div>
  );
}

export function UserInfoSection({ user }: UserInfoSectionProps) {
  const t = useTranslations('profile.user');
  const platform = usePlatform();
  const queryClient = useQueryClient();

  const [showLinkTelegramDialog, setShowLinkTelegramDialog] = useState(false);
  const [showAddEmailDialog, setShowAddEmailDialog] = useState(false);
  const [showTelegramDetails, setShowTelegramDetails] = useState(false);
  const [showEmailDetails, setShowEmailDetails] = useState(false);

  const displayName = user.display_name ?? 'User';

  const initials = useMemo(() => {
    const first = user.display_name?.[0] ?? user.username?.[0] ?? 'U';
    return first.toUpperCase();
  }, [user.display_name, user.username]);

  const authMethod = platform.isTelegram ? 'telegram' : 'web';
  const hasTelegram = !!user.telegram_id;
  const hasEmail = !!user.email;

  const memberSince = user.created_at
    ? new Date(user.created_at).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })
    : null;

  const formatGender = (male: boolean | null | undefined) => {
    if (male === null || male === undefined) return '—';
    return male ? t('gender.male') : t('gender.female');
  };

  const { mutate: logout, isPending: isLoggingOut } = useLogoutAuthLogoutPost({
    mutation: {
      onSuccess: () => {
        void queryClient.invalidateQueries({ queryKey: getCurrentUserUsersMeGetQueryKey() });
      },
    },
  });

  const handleLogout = () => {
    logout();
  };

  const handleLinkSuccess = () => {
    void queryClient.invalidateQueries({ queryKey: getCurrentUserUsersMeGetQueryKey() });
  };

  return (
    <ProfileSection icon="&#128100;" title={t('title')}>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center gap-4">
          <Avatar className="h-16 w-16">
            {user.avatar_url && <AvatarImage src={user.avatar_url} alt={displayName} />}
            <AvatarFallback className="text-xl">{initials}</AvatarFallback>
          </Avatar>
          <div className="flex-1">
            <p className="font-semibold text-lg">{displayName}</p>
            <p className="text-sm text-muted-foreground">@{user.username ?? 'user'}</p>
            {memberSince && (
              <p className="text-xs text-muted-foreground">{t('memberSince', { date: memberSince })}</p>
            )}
          </div>
        </div>

        {/* Activity Stats */}
        <div>
          <p className="text-xs font-semibold text-muted-foreground mb-3">{t('sections.activity')}</p>
          <div className="grid grid-cols-3 gap-2">
            <StatCard
              icon={Flame}
              value={user.current_streak ?? 0}
              label={t('stats.currentStreak')}
            />
            <StatCard
              icon={Trophy}
              value={user.best_streak ?? 0}
              label={t('stats.bestStreak')}
            />
            <StatCard
              icon={Calendar}
              value={user.total_active_days ?? 0}
              label={t('stats.totalDays')}
            />
          </div>
        </div>

        {/* Preferences */}
        <div>
          <p className="text-xs font-semibold text-muted-foreground mb-2">{t('sections.preferences')}</p>
          <div className="divide-y">
            <PreferenceRow label={t('prefs.language')} value={user.language_code ?? ''} />
            <PreferenceRow label={t('prefs.timezone')} value={user.timezone ?? ''} />
            <PreferenceRow label={t('prefs.birthDate')} value={user.birth_date ?? ''} />
            <PreferenceRow label={t('prefs.gender')} value={formatGender(user.male)} />
          </div>
        </div>

        {/* Auth Methods */}
        <div>
          <p className="text-xs font-semibold text-muted-foreground mb-3">{t('sections.authMethods')}</p>
          <div className="space-y-2">
            <AuthMethodCard
              icon={Smartphone}
              title="Telegram"
              isLinked={hasTelegram}
              subtitle={user.tg_username ? `@${user.tg_username}` : user.tg_first_name ?? undefined}
              onLink={() => { setShowLinkTelegramDialog(true); }}
              onShowDetails={hasTelegram ? () => { setShowTelegramDetails(!showTelegramDetails); } : undefined}
              showDetails={showTelegramDetails}
            >
              <DetailRow label="ID" value={user.telegram_id} mono />
              <DetailRow label={t('tg.firstName')} value={user.tg_first_name} />
              <DetailRow label={t('tg.lastName')} value={user.tg_last_name} />
              <DetailRow label={t('tg.username')} value={user.tg_username} />
              <DetailRow label={t('tg.languageCode')} value={user.tg_language_code} />
              <DetailRow label={t('tg.isPremium')} value={user.tg_is_premium} />
              <DetailRow label={t('tg.isBot')} value={user.tg_is_bot} />
            </AuthMethodCard>

            <AuthMethodCard
              icon={Mail}
              title="Email"
              isLinked={hasEmail}
              subtitle={user.email ?? undefined}
              onLink={() => { setShowAddEmailDialog(true); }}
              onShowDetails={hasEmail ? () => { setShowEmailDetails(!showEmailDetails); } : undefined}
              showDetails={showEmailDetails}
            >
              <DetailRow label={t('email.address')} value={user.email} />
              <DetailRow label={t('email.verified')} value={user.email_verified} />
              <DetailRow label={t('email.verifiedAt')} value={user.email_verified_at} />
              <DetailRow label={t('email.lastLogin')} value={user.last_login_at} />
            </AuthMethodCard>
          </div>
        </div>

        {/* Logout button (only for web auth) */}
        {authMethod === 'web' && (
          <Button
            variant="outline"
            className="w-full text-destructive hover:text-destructive hover:bg-destructive/10"
            disabled={isLoggingOut}
            onClick={handleLogout}
          >
            <LogOut className={`w-4 h-4 mr-2 ${isLoggingOut ? 'animate-spin' : ''}`} />
            {isLoggingOut ? t('loggingOut') : t('logout')}
          </Button>
        )}
      </div>

      <LinkTelegramDialog
        open={showLinkTelegramDialog}
        onOpenChange={setShowLinkTelegramDialog}
        onSuccess={handleLinkSuccess}
      />

      <AddEmailDialog
        open={showAddEmailDialog}
        onOpenChange={setShowAddEmailDialog}
        onSuccess={handleLinkSuccess}
      />
    </ProfileSection>
  );
}

// apps/template-vue/frontend/src/app/presentation/components/profile/UserInfoSection.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { usePlatform } from '@core/platform'
import { useLogoutAuthLogoutPost, getCurrentUserUsersMeGetQueryKey } from '@/gen/hooks'
import { useQueryClient } from '@tanstack/vue-query'
import ProfileSection from './ProfileSection.vue'
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import {
  LogOut,
  Smartphone,
  Mail,
  ChevronDown,
  ChevronUp,
  Flame,
  Trophy,
  Calendar,
  Check,
  Plus
} from 'lucide-vue-next'
import LinkTelegramModal from './LinkTelegramModal.vue'
import AddEmailModal from './AddEmailModal.vue'
import type { UserSchema } from '@/gen/models'

const props = defineProps<{
  user: UserSchema
}>()

const { t } = useI18n()
const platform = usePlatform()
const queryClient = useQueryClient()

const showLinkTelegramModal = ref(false)
const showAddEmailModal = ref(false)
const showTelegramDetails = ref(false)
const showEmailDetails = ref(false)

const displayName = computed(() => props.user.display_name || 'User')

const initials = computed(() => {
  const first = props.user.display_name?.[0] ?? props.user.username?.[0] ?? 'U'
  return first.toUpperCase()
})

const authMethod = computed(() => platform.isTelegram ? 'telegram' : 'web')
const hasTelegram = computed(() => !!props.user.telegram_id)
const hasEmail = computed(() => !!props.user.email)

const memberSince = computed(() => {
  if (!props.user.created_at) return null
  return new Date(props.user.created_at).toLocaleDateString(undefined, { month: 'short', year: 'numeric' })
})

const formatGender = (male: boolean | null | undefined) => {
  if (male === null || male === undefined) return '—'
  return male ? t('profile.user.gender.male') : t('profile.user.gender.female')
}

const formatDetailValue = (value: unknown): string => {
  if (value === null || value === undefined) return '—'
  if (typeof value === 'boolean') return value ? t('common.yes') : t('common.no')
  return String(value)
}

const { mutate: logout, isPending: isLoggingOut } = useLogoutAuthLogoutPost({
  mutation: {
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: getCurrentUserUsersMeGetQueryKey() })
    }
  }
})

const handleLogout = () => {
  logout()
}

const handleLinkSuccess = () => {
  queryClient.invalidateQueries({ queryKey: getCurrentUserUsersMeGetQueryKey() })
}
</script>

<template>
  <ProfileSection icon="&#128100;" :title="t('profile.user.title')">
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center gap-4">
        <Avatar class="h-16 w-16">
          <AvatarImage v-if="props.user.avatar_url" :src="props.user.avatar_url" :alt="displayName" />
          <AvatarFallback class="text-xl">{{ initials }}</AvatarFallback>
        </Avatar>
        <div class="flex-1">
          <p class="font-semibold text-lg">{{ displayName }}</p>
          <p class="text-sm text-muted-foreground">@{{ props.user.username || 'user' }}</p>
          <p v-if="memberSince" class="text-xs text-muted-foreground">
            {{ t('profile.user.memberSince', { date: memberSince }) }}
          </p>
        </div>
      </div>

      <!-- Activity Stats -->
      <div>
        <p class="text-xs font-semibold text-muted-foreground mb-3">{{ t('profile.user.sections.activity') }}</p>
        <div class="grid grid-cols-3 gap-2">
          <div class="bg-muted rounded-lg p-3 text-center">
            <Flame class="h-4 w-4 mx-auto mb-1 text-muted-foreground" />
            <p class="text-2xl font-bold">{{ props.user.current_streak ?? 0 }}</p>
            <p class="text-xs text-muted-foreground">{{ t('profile.user.stats.currentStreak') }}</p>
          </div>
          <div class="bg-muted rounded-lg p-3 text-center">
            <Trophy class="h-4 w-4 mx-auto mb-1 text-muted-foreground" />
            <p class="text-2xl font-bold">{{ props.user.best_streak ?? 0 }}</p>
            <p class="text-xs text-muted-foreground">{{ t('profile.user.stats.bestStreak') }}</p>
          </div>
          <div class="bg-muted rounded-lg p-3 text-center">
            <Calendar class="h-4 w-4 mx-auto mb-1 text-muted-foreground" />
            <p class="text-2xl font-bold">{{ props.user.total_active_days ?? 0 }}</p>
            <p class="text-xs text-muted-foreground">{{ t('profile.user.stats.totalDays') }}</p>
          </div>
        </div>
      </div>

      <!-- Preferences -->
      <div>
        <p class="text-xs font-semibold text-muted-foreground mb-2">{{ t('profile.user.sections.preferences') }}</p>
        <div class="divide-y">
          <div class="flex items-center justify-between py-2">
            <span class="text-sm text-muted-foreground">{{ t('profile.user.prefs.language') }}</span>
            <span class="text-sm">{{ props.user.language_code || '—' }}</span>
          </div>
          <div class="flex items-center justify-between py-2">
            <span class="text-sm text-muted-foreground">{{ t('profile.user.prefs.timezone') }}</span>
            <span class="text-sm">{{ props.user.timezone || '—' }}</span>
          </div>
          <div class="flex items-center justify-between py-2">
            <span class="text-sm text-muted-foreground">{{ t('profile.user.prefs.birthDate') }}</span>
            <span class="text-sm">{{ props.user.birth_date || '—' }}</span>
          </div>
          <div class="flex items-center justify-between py-2">
            <span class="text-sm text-muted-foreground">{{ t('profile.user.prefs.gender') }}</span>
            <span class="text-sm">{{ formatGender(props.user.male) }}</span>
          </div>
        </div>
      </div>

      <!-- Auth Methods -->
      <div>
        <p class="text-xs font-semibold text-muted-foreground mb-3">{{ t('profile.user.sections.authMethods') }}</p>
        <div class="space-y-2">
          <!-- Telegram Auth -->
          <div class="border rounded-lg p-3">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <div class="bg-muted rounded-full p-2">
                  <Smartphone class="h-4 w-4" />
                </div>
                <div>
                  <p class="text-sm font-medium">Telegram</p>
                  <p class="text-xs text-muted-foreground">
                    {{ hasTelegram ? (props.user.tg_username ? `@${props.user.tg_username}` : props.user.tg_first_name) : t('common.notConnected') }}
                  </p>
                </div>
              </div>
              <div class="flex items-center gap-2">
                <template v-if="hasTelegram">
                  <Check class="h-4 w-4 text-green-500" />
                  <Button variant="ghost" size="sm" @click="showTelegramDetails = !showTelegramDetails">
                    <ChevronUp v-if="showTelegramDetails" class="h-4 w-4" />
                    <ChevronDown v-else class="h-4 w-4" />
                  </Button>
                </template>
                <Button v-else variant="outline" size="sm" @click="showLinkTelegramModal = true">
                  <Plus class="h-3 w-3 mr-1" />
                  {{ t('common.link') }}
                </Button>
              </div>
            </div>
            <div v-if="showTelegramDetails && hasTelegram" class="mt-3 pt-3 border-t space-y-1">
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">ID</span>
                <span class="font-mono">{{ props.user.telegram_id }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.tg.firstName') }}</span>
                <span>{{ formatDetailValue(props.user.tg_first_name) }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.tg.lastName') }}</span>
                <span>{{ formatDetailValue(props.user.tg_last_name) }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.tg.username') }}</span>
                <span>{{ formatDetailValue(props.user.tg_username) }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.tg.languageCode') }}</span>
                <span>{{ formatDetailValue(props.user.tg_language_code) }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.tg.isPremium') }}</span>
                <span>{{ formatDetailValue(props.user.tg_is_premium) }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.tg.isBot') }}</span>
                <span>{{ formatDetailValue(props.user.tg_is_bot) }}</span>
              </div>
            </div>
          </div>

          <!-- Email Auth -->
          <div class="border rounded-lg p-3">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <div class="bg-muted rounded-full p-2">
                  <Mail class="h-4 w-4" />
                </div>
                <div>
                  <p class="text-sm font-medium">Email</p>
                  <p class="text-xs text-muted-foreground">
                    {{ hasEmail ? props.user.email : t('common.notConnected') }}
                  </p>
                </div>
              </div>
              <div class="flex items-center gap-2">
                <template v-if="hasEmail">
                  <Check class="h-4 w-4 text-green-500" />
                  <Button variant="ghost" size="sm" @click="showEmailDetails = !showEmailDetails">
                    <ChevronUp v-if="showEmailDetails" class="h-4 w-4" />
                    <ChevronDown v-else class="h-4 w-4" />
                  </Button>
                </template>
                <Button v-else variant="outline" size="sm" @click="showAddEmailModal = true">
                  <Plus class="h-3 w-3 mr-1" />
                  {{ t('common.link') }}
                </Button>
              </div>
            </div>
            <div v-if="showEmailDetails && hasEmail" class="mt-3 pt-3 border-t space-y-1">
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.email.address') }}</span>
                <span>{{ props.user.email }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.email.verified') }}</span>
                <span>{{ formatDetailValue(props.user.email_verified) }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.email.verifiedAt') }}</span>
                <span>{{ formatDetailValue(props.user.email_verified_at) }}</span>
              </div>
              <div class="flex items-center justify-between text-xs">
                <span class="text-muted-foreground">{{ t('profile.user.email.lastLogin') }}</span>
                <span>{{ formatDetailValue(props.user.last_login_at) }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Logout button (only for web auth) -->
      <Button
        v-if="authMethod === 'web'"
        variant="outline"
        class="w-full text-destructive hover:text-destructive hover:bg-destructive/10"
        :disabled="isLoggingOut"
        @click="handleLogout"
      >
        <LogOut class="w-4 h-4 mr-2" />
        {{ isLoggingOut ? t('profile.user.loggingOut') : t('profile.user.logout') }}
      </Button>
    </div>

    <LinkTelegramModal
      v-model:open="showLinkTelegramModal"
      @success="handleLinkSuccess"
    />

    <AddEmailModal
      v-model:open="showAddEmailModal"
      @success="handleLinkSuccess"
    />
  </ProfileSection>
</template>
