// apps/template-vue/frontend/src/app/presentation/screens/Profile.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useGetCurrentUserUsersMeGet } from '@/gen/hooks'

import UserInfoSection from '@app/presentation/components/profile/UserInfoSection.vue'
import FriendsSection from '@app/presentation/components/profile/FriendsSection.vue'
import NotificationSection from '@app/presentation/components/profile/NotificationSection.vue'
import TelegramSection from '@app/presentation/components/profile/TelegramSection.vue'
import LoginPrompt from '@app/presentation/components/profile/LoginPrompt.vue'
import AuthRequired from '@app/presentation/components/profile/AuthRequired.vue'
import RbacDemo from '@app/presentation/components/profile/RbacDemo.vue'

const { t } = useI18n()

const { data: user, isLoading } = useGetCurrentUserUsersMeGet()
// User is authenticated if they have a registered account (not a guest)
const isAuthenticated = computed(() => user.value?.user_type === 'REGISTERED')
</script>

<template>
  <div class="py-6 space-y-6">
    <!-- Header with blur-in effect (#1, #2) -->
    <div class="text-center mb-8">
      <h1
        class="text-2xl font-bold mb-2 motion-blur-in-[6px] motion-scale-in-[0.95] motion-opacity-in-[0%] motion-duration-[0.5s] motion-duration-[0.7s]/blur motion-ease-spring-smooth"
      >
        {{ t('profile.title') }}
      </h1>
      <p
        class="text-muted-foreground motion-blur-in-[4px] motion-opacity-in-[0%] motion-duration-[0.4s] motion-delay-[0.15s] motion-ease-spring-smooth"
      >
        {{ t('profile.subtitle') }}
      </p>
    </div>

    <!-- Loading state with pulse (#10) -->
    <div v-if="isLoading" class="text-center py-8">
      <p class="text-muted-foreground motion-preset-pulse motion-duration-[1.5s] motion-loop-infinite">
        {{ t('common.loading') }}
      </p>
    </div>

    <template v-else>
      <!-- User Info - shows login prompt or user data (#14) -->
      <Transition
        enter-active-class="motion-scale-in-[0.95] motion-blur-in-[2px] motion-opacity-in-[0%] motion-duration-[0.3s] motion-ease-spring-smooth"
        leave-active-class="motion-opacity-out-[0%] motion-duration-[0.2s]"
        mode="out-in"
      >
        <div v-if="isAuthenticated && user" key="user-info">
          <UserInfoSection :user="user" />
        </div>
        <div v-else key="login-prompt">
          <LoginPrompt />
        </div>
      </Transition>

      <!-- Platform section - available for all (#3, #4) -->
      <div
        class="motion-opacity-in-[0%] motion-translate-y-in-[20px] motion-blur-in-[3px] motion-duration-[0.4s] motion-duration-[0.6s]/blur motion-delay-[0.1s] motion-ease-spring-smooth"
      >
        <TelegramSection />
      </div>

      <!-- Auth-required sections with staggered animations (#3, #15) -->
      <div
        class="motion-opacity-in-[0%] motion-translate-y-in-[20px] motion-blur-in-[3px] motion-duration-[0.4s] motion-duration-[0.6s]/blur motion-delay-[0.18s] motion-ease-spring-smooth"
      >
        <AuthRequired :locked="!isAuthenticated">
          <FriendsSection />
        </AuthRequired>
      </div>

      <div
        class="motion-opacity-in-[0%] motion-translate-y-in-[20px] motion-blur-in-[3px] motion-duration-[0.4s] motion-duration-[0.6s]/blur motion-delay-[0.26s] motion-ease-spring-smooth"
      >
        <AuthRequired :locked="!isAuthenticated">
          <NotificationSection />
        </AuthRequired>
      </div>

      <!-- RBAC Demo -->
      <div
        class="motion-opacity-in-[0%] motion-translate-y-in-[20px] motion-blur-in-[3px] motion-duration-[0.4s] motion-duration-[0.6s]/blur motion-delay-[0.34s] motion-ease-spring-smooth"
      >
        <RbacDemo />
      </div>
    </template>

    <!-- CTA card with bounce entrance (#12) and hover glow (#19) -->
    <div
      class="group bg-muted/50 rounded-xl p-4 text-center motion-scale-in-[0.9] motion-opacity-in-[0%] motion-duration-[0.5s] motion-delay-[0.37s] motion-ease-spring-bouncy transition-all duration-300 hover:bg-muted/70 hover:shadow-lg hover:shadow-primary/10"
    >
      <p class="text-sm text-muted-foreground mb-2">
        {{ t('profile.ctaText') }}
      </p>
      <router-link
        to="/demo"
        class="text-primary hover:underline font-medium inline-flex items-center gap-1"
      >
        {{ t('profile.ctaLink') }}
        <!-- CTA arrow wiggle (#6) -->
        <span class="inline-block transition-transform duration-200 group-hover:translate-x-1 group-hover:motion-preset-wiggle-sm">
          &rarr;
        </span>
      </router-link>
    </div>
  </div>
</template>

// apps/template-react/frontend/app/[locale]/(app)/profile/page.tsx
'use client';

import { useTranslations } from 'next-intl';

import { getErrorMessage } from '@tma-platform/core-react/errors';
import { useGetCurrentUserUsersMeGet } from '@/src/gen/hooks';
import {
  UserInfoSection,
  TelegramSection,
  FriendsSection,
  NotificationSection,
  LoginPrompt,
  AuthRequired,
  RbacDemo,
} from '@/components/profile';
import { Link } from '@/i18n/navigation';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';

export default function ProfilePage() {
  const t = useTranslations('profile');

  const { data: user, isLoading, error, refetch } = useGetCurrentUserUsersMeGet();
  // User is authenticated if they have a registered account (not a guest)
  const isAuthenticated = user?.user_type === 'REGISTERED';

  if (isLoading) {
    return (
      <div className="py-6 text-center">
        <p className="text-muted-foreground animate-pulse">{t('loading', { defaultValue: 'Loading...' })}</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="py-6 px-4">
        <Alert variant="destructive" className="motion-preset-shake motion-duration-[0.4s]">
          <AlertDescription className="flex items-center justify-between gap-4">
            <span>{getErrorMessage(error)}</span>
            <Button
              size="sm"
              variant="outline"
              className="shrink-0"
              onClick={() => refetch()}
            >
              {t('retry', { defaultValue: 'Retry' })}
            </Button>
          </AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <div className="py-6 space-y-4">
      {/* Header - Hero moment with dramatic emphasis */}
      <div className="text-center mb-6">
        <h1 className="text-2xl font-bold mb-2 motion-blur-in-[10px] motion-scale-in-[0.95] motion-opacity-in-[0%] motion-duration-[0.7s] motion-duration-[1s]/blur motion-ease-spring-smooth">
          {t('title')}
        </h1>
        <p className="text-muted-foreground motion-blur-in-[5px] motion-opacity-in-[0%] motion-translate-y-in-[10px] motion-duration-[0.5s] motion-delay-[0.25s] motion-ease-spring-smooth">
          {t('subtitle')}
        </p>
      </div>

      {/* User Info / Login Prompt */}
      <div className="motion-opacity-in-[0%] motion-scale-in-[0.98] motion-blur-in-[3px] motion-duration-[0.55s] motion-delay-[0.35s] motion-ease-spring-smooth">
        {isAuthenticated ? (
          <UserInfoSection user={user} />
        ) : (
          <LoginPrompt />
        )}
      </div>

      {/* Platform */}
      <div className="motion-opacity-in-[0%] motion-translate-y-in-[30px] motion-blur-in-[4px] motion-duration-[0.5s] motion-delay-[0.5s] motion-ease-spring-smooth">
        <TelegramSection />
      </div>

      {/* Friends */}
      <div className="motion-opacity-in-[0%] motion-translate-y-in-[30px] motion-blur-in-[4px] motion-duration-[0.5s] motion-delay-[0.6s] motion-ease-spring-smooth">
        <AuthRequired locked={!isAuthenticated}>
          <FriendsSection />
        </AuthRequired>
      </div>

      {/* Notifications */}
      <div className="motion-opacity-in-[0%] motion-translate-y-in-[30px] motion-blur-in-[4px] motion-duration-[0.5s] motion-delay-[0.7s] motion-ease-spring-smooth">
        <AuthRequired locked={!isAuthenticated}>
          <NotificationSection />
        </AuthRequired>
      </div>

      {/* RBAC Demo */}
      <div className="motion-opacity-in-[0%] motion-translate-y-in-[30px] motion-blur-in-[4px] motion-duration-[0.5s] motion-delay-[0.8s] motion-ease-spring-smooth">
        <RbacDemo />
      </div>

      {/* CTA - Final flourish with glow effect */}
      <div className="motion-scale-in-[0.95] motion-opacity-in-[0%] motion-duration-[0.5s] motion-delay-[0.9s] motion-ease-spring-bouncy group relative overflow-hidden bg-muted/50 rounded-xl p-4 text-center transition-all duration-300 hover:bg-muted/70 hover:shadow-xl hover:shadow-primary/15">
        {/* Animated border glow on hover */}
        <div className="absolute inset-0 rounded-xl bg-gradient-to-r from-primary/0 via-primary/10 to-primary/0 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

        <p className="relative text-sm text-muted-foreground mb-2">Want to copy these patterns?</p>
        <Link
          href="/demo"
          className="relative text-primary hover:underline font-medium inline-flex items-center gap-1"
        >
          See TanStack Query demos{' '}
          <span className="inline-block transition-transform duration-300 group-hover:translate-x-2">
            &rarr;
          </span>
        </Link>
      </div>
    </div>
  );
}
