// apps/template-react/frontend/app/[locale]/(app)/admin/page.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useAppInit } from '@/providers/AppInitProvider';
import { useGetMyPermissionsAdminMeGet } from '@/src/gen/hooks/useGetMyPermissionsAdminMeGet';
import { useGetStatsAdminStatsGet } from '@/src/gen/hooks/useGetStatsAdminStatsGet';
import { YourAccessCard } from '@/components/admin/YourAccessCard';
import { StatsCards } from '@/components/admin/StatsCards';
import { ProtectedActionDemo } from '@/components/admin/ProtectedActionDemo';

export default function AdminPage() {
  const { user, isLoading } = useAppInit();
  const router = useRouter();

  const { data: permissions } = useGetMyPermissionsAdminMeGet();
  const { data: stats } = useGetStatsAdminStatsGet();

  // Redirect non-admins
  if (!isLoading && user && !['admin', 'owner'].includes(user.role ?? '')) {
    router.replace('/');
    return null;
  }

  if (isLoading) return <div className="p-6 animate-pulse">Loading...</div>;

  return (
    <div className="container py-6 space-y-6 max-w-4xl mx-auto">
      {/* Header - Hero moment */}
      <div className="text-center mb-6">
        <h1 className="text-2xl font-bold mb-2 motion-blur-in-[10px] motion-scale-in-[0.95] motion-opacity-in-[0%] motion-duration-[0.7s] motion-duration-[1s]/blur motion-ease-spring-smooth">
          RBAC Demo
        </h1>
        <p className="text-muted-foreground motion-blur-in-[5px] motion-opacity-in-[0%] motion-translate-y-in-[10px] motion-duration-[0.5s] motion-delay-[0.25s] motion-ease-spring-smooth">
          This page demonstrates role-based access control
        </p>
      </div>

      {/* Your role and permissions */}
      <div className="motion-opacity-in-[0%] motion-translate-y-in-[30px] motion-blur-in-[4px] motion-duration-[0.5s] motion-delay-[0.35s] motion-ease-spring-smooth">
        <YourAccessCard permissions={permissions} />
      </div>

      {/* Safe aggregate stats */}
      <div className="motion-opacity-in-[0%] motion-translate-y-in-[30px] motion-blur-in-[4px] motion-duration-[0.5s] motion-delay-[0.5s] motion-ease-spring-smooth">
        <StatsCards stats={stats} />
      </div>

      {/* Try protected action */}
      <div className="motion-opacity-in-[0%] motion-translate-y-in-[30px] motion-blur-in-[4px] motion-duration-[0.5s] motion-delay-[0.65s] motion-ease-spring-smooth">
        <ProtectedActionDemo canExecute={permissions?.permissions.includes('protected_actions') ?? false} />
      </div>
    </div>
  );
}

// apps/template/frontend/src/app/presentation/screens/Admin.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { useRouter } from 'vue-router';
import { useGetCurrentUserUsersMeGet } from '@gen/hooks';
import { useGetMyPermissionsAdminMeGet } from '@gen/hooks/useGetMyPermissionsAdminMeGet';
import { useGetStatsAdminStatsGet } from '@gen/hooks/useGetStatsAdminStatsGet';
import YourAccessCard from '@app/presentation/components/admin/YourAccessCard.vue';
import StatsCards from '@app/presentation/components/admin/StatsCards.vue';
import ProtectedActionDemo from '@app/presentation/components/admin/ProtectedActionDemo.vue';

const router = useRouter();
const { data: user, isLoading } = useGetCurrentUserUsersMeGet();

const isAdmin = computed(() => !!user.value && ['admin', 'owner'].includes(user.value.role ?? ''));

const { data: permissions } = useGetMyPermissionsAdminMeGet({
  query: {
    enabled: () => isAdmin.value,
  }
});
const { data: stats } = useGetStatsAdminStatsGet({
  query: {
    enabled: () => isAdmin.value,
  }
});

// Redirect non-admins
watch([user, isLoading], ([currentUser, loading]) => {
  if (!loading && currentUser && !['admin', 'owner'].includes(currentUser.role ?? '')) {
    router.replace('/demo');
  }
});
</script>

<template>
  <div class="container py-6 space-y-6 max-w-4xl mx-auto">
    <div v-if="isLoading" class="p-6">
      Loading...
    </div>
    <template v-else-if="isAdmin">
      <!-- Header with blur-in effect -->
      <div class="text-center mb-8">
        <h1
          class="text-2xl font-bold mb-2 motion-blur-in-[6px] motion-scale-in-[0.95] motion-opacity-in-[0%] motion-duration-[0.5s] motion-duration-[0.7s]/blur motion-ease-spring-smooth"
        >
          RBAC Demo
        </h1>
        <p
          class="text-muted-foreground motion-blur-in-[4px] motion-opacity-in-[0%] motion-duration-[0.4s] motion-delay-[0.15s] motion-ease-spring-smooth"
        >
          This page demonstrates role-based access control
        </p>
      </div>

      <!-- Your role and permissions -->
      <div
        class="motion-opacity-in-[0%] motion-translate-y-in-[20px] motion-blur-in-[3px] motion-duration-[0.4s] motion-duration-[0.6s]/blur motion-delay-[0.2s] motion-ease-spring-smooth"
      >
        <YourAccessCard :permissions="permissions" />
      </div>

      <!-- Safe aggregate stats -->
      <div
        class="motion-opacity-in-[0%] motion-translate-y-in-[20px] motion-blur-in-[3px] motion-duration-[0.4s] motion-duration-[0.6s]/blur motion-delay-[0.3s] motion-ease-spring-smooth"
      >
        <StatsCards :stats="stats" />
      </div>

      <!-- Try protected action -->
      <div
        class="motion-opacity-in-[0%] motion-translate-y-in-[20px] motion-blur-in-[3px] motion-duration-[0.4s] motion-duration-[0.6s]/blur motion-delay-[0.4s] motion-ease-spring-smooth"
      >
        <ProtectedActionDemo :can-execute="permissions?.permissions.includes('protected_actions') ?? false" />
      </div>

      <!-- CTA card with bounce entrance and hover glow -->
      <div
        class="group bg-muted/50 rounded-xl p-4 text-center motion-scale-in-[0.9] motion-opacity-in-[0%] motion-duration-[0.5s] motion-delay-[0.5s] motion-ease-spring-bouncy transition-all duration-300 hover:bg-muted/70 hover:shadow-lg hover:shadow-primary/10"
      >
        <p class="text-sm text-muted-foreground mb-2">
          {{ $t('admin.ctaText') }}
        </p>
        <router-link
          to="/demo"
          class="text-primary hover:underline font-medium inline-flex items-center gap-1"
        >
          {{ $t('admin.ctaLink') }}
          <!-- CTA arrow wiggle -->
          <span
            class="inline-block transition-transform duration-200 group-hover:translate-x-1 group-hover:motion-preset-wiggle-sm"
          >
            &rarr;
          </span>
        </router-link>
      </div>
    </template>
  </div>
</template>
